### ISSUE TITLE
Still broken?

### ISSUE THREAD

**Issue by JamesThack** [WUBBSY/RGBDeck#1]
Hi, I am a mega RGB enthusiast and use OpenRGB in my pc, I have a steam deck and this project is something I would love to do but I saw the warning. Sorry if this is the wrong place to ask but has there been any progress in fixing this issue, or a community to talk about RGBDeck :p

**Comment by WUBBSY** [comment]
Hi, I have experimented with connecting it directly to the battery via a voltage regulator (Pololu S13VxF5) but the Steam Deck seams to be pretty picky about its battery and I would get wired behavior, like not starting again after powering off or sleep, until I disconnect the the regulator. 
It's probably more a problem with the MOSFET switching on and of the regulator but it's needed. Else the LEDs don't turn off with the Device. 

I then switch out the LEDs (now 111 of them and smaller [Pictures](https://twitter.com/mswubbsy/status/1627085463273218050?s=46&t=evQACBIeF-DxrI6jbMfGlg)) and powered them again from the 5V of the controller board without any issue. 
I keep them really dim, 5% if I remember, which is still relatively bright. And the effect is still really cool. Just the color transitions are not as smooth. 
I think the power draw from everything was about 0.1-0.15w if I remember. 

My Steam Deck still works flawlessly. So it's hard to say if was maybe something else or if it's just because I keep them dim. 

There are a few post on my [Twitter](https://twitter.com/mswubbsy) about my tests and the build. 

Now to try and answer if it's safe. 
I mean if you use fewer LEDs (OpenRGB can only control up to 84) and keep them at a moderate level you should probably be fine. 
I don't use my Steam Deck too much but often Push it hard and never had any problems. 
A risk is always involved but things can always happen. 

I'm sorry that I can't give you conclusive answers. I hope I can try it again when I have more time, especially now that there are translucent front shells. 

I still hope I could help you a bit. 

Have a Great day
~Wubbsy

**Comment by JamesThack** [comment]
Thanks for the big explaination :D Im probs gonna avoid it for now mostly because I am not that rich and I spent a fortune on my steam deck haha, thanks for working on this project though it is really cool! I followed ur twitter so il keep up to date <3
